/*
 * Copyright (C) 2020 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.example.android.unscramble.ui.game


const val MAX_NO_OF_WORDS = 5
const val SCORE_INCREASE = 20

// List with all the words for the Game
val allWordsList: List<String> =
    listOf("app",
        "auto",
        "ant",
        "alphabet",
        "all",
        "anand",
        "apple",
        "ball",
        "bat",
        "bench",
        "best",
        "boy",
        "book",
        "bench",
        "camera",
        "cat",
        "car",
        "cook",
        "cow",
        "chat",
        "chil",
        "class",
        "clap",
        "coffee",
        "color",
        "creat",
        "copy",
        "dance",
        "day",
        "dry",
        "door",
        "dine",
        "dream",
        "dusk",
        "eat",
        "elephant",
        "emerald",
        "eerie",
        "electric",
        "finish",
        "flower",
        "follow",
        "fox",
        "frame",
        "free",
        "front",
        "green",
        "guitar",
        "grow",
        "glass",
        "girl",
        "great",
        "game",
        "hair",
        "half",
        "home",
        "happen",
        "honey",
        "hurry",
        "high",
        "ice",
        "igloo",
        "invest",
        "invite",
        "icon",
        "intro",
        "joke",
        "joy",
        "journey",
        "jump",
        "join",
        "key",
        "keyboard",
        "kitchen",
        "kind",
        "land",
        "late",
        "laugh",
        "learn",
        "lemon",
        "letter",
        "lily",
        "maze",
        "mouse",
        "melody",
        "minute",
        "monument",
        "moon",
        "motorcycle",
        "mountain",
        "music",
        "north",
        "nose",
        "night",
        "name",
        "never",
        "number",
        "opposite",
        "octopus",
        "oil",
        "order",
        "open",
        "polar",
        "pen",
        "paint",
        "person",
        "paper",
        "pinnk",
        "pizza",
        "pet",
        "present",
        "puppy",
        "puzzle",
        "recipe",
        "release",
        "red",
        "round",
        "rewind",
        "room",
        "run",
        "sad",
        "seed",
        "ship",
        "shirt",
        "should",
        "small",
        "space",
        "stargazing",
        "skill",
        "street",
        "style",
        "sun",
        "taxi",
        "tidy",
        "timer",
        "toy",
        "tooth",
        "tour",
        "travel",
        "truck",
        "under",
        "useful",
        "unique",
        "view",
        "water",
        "world",
        "winter",
        "well",
        "wire",
        "x-ray",
        "yoga",
        "yellow",
        "yoyo",
        "you",
        "year",
        "zebra",
        "zoo")
